Repository pbiering/ipv6calc, pull requests merged in 2021-05, with the labels that each got.

#20 Shell scripts refinement
  autogen-all-variants.sh
  autogen-support.sh
  autogen.sh
  databases/as-assignment/check-run-create.sh
  databases/cc-assignment/check-run-create.sh
  databases/tools/test_db_lookup.sh
  ipv6calc/test_ipv6calc.sh
  ipv6calc/test_ipv6calc_anonymization.sh
  ipv6calc/test_ipv6calc_filter.sh
  ipv6calc/test_showinfo.sh
  ipv6calcweb/create_ipv6calcweb-cgi.sh
  ipv6calcweb/test_ipv6calcweb.sh
  ipv6calcweb/test_ipv6calcweb_form.sh
  ipv6loganon/test_ipv6loganon.sh
  ipv6logstats/test_ipv6logstats.sh
  mod_ipv6calc/test_mod_ipv6calc.sh
  tools/DBIP-update.sh.in
  tools/GeoIP-update.sh.in
  tools/IP2Location-update.sh.in
  tools/ipv6calc-db-update.sh.in
  tools/ipv6calc-registries-check-run-create.sh
  tools/ipv6calc-update-registries.sh
Labels: enhancement

#19 add support for compressed IPv4 addresses, like 10/8
  ipv6calc/test_ipv6calc.sh
  lib/ipv6calchelp.c
  lib/ipv6calctypes.h
  lib/libipv4addr.c
  lib/libipv6calc.c
Labels: enhancement

#21 Fix tests on OpenBSD
  ipv6calcweb/create_ipv6calcweb-cgi.sh
  ipv6logstats/test_ipv6logstats.sh
Labels: bug

#22 try to fix cygwin compilation issue related to -Werror=char-subscripts
  configure
  configure.in
  databases/lib/libipv6calc_db_wrapper.c
Labels: bug, enhancement

#27 Fix enhance ip2location
  ChangeLog
  VERSION
  autogen-all-variants.sh
  autogen-support.sh
  configure
  configure.in
  contrib/ipv6calc.spec
  databases/lib/libipv6calc_db_wrapper_IP2Location.c
  databases/lib/libipv6calc_db_wrapper_IP2Location.h
  tools/IP2Location-update.sh.in
Labels: bug, enhancement
